FROM python:3.12-slim
RUN apt-get update && apt-get install -y libpq-dev pkg-config libicu-dev g++ && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY . .
RUN pip install -e ".[dev]"
CMD ["python", "-m", "app.main"]
